### ISSUE TITLE
problem with simpy

### ISSUE THREAD

**Issue by monperrus** [linzhp/Codevo3#3]
Hi,

I try to run `python3 codevo/simulate.py 200000` and get the following error:

    ImportError: No module named simpy

On my Linux machine, python is case-sensitive and `import SimPy ` is a fix.

However, then it fails at `env = simpy.Environment()` and `env = SimPy.Environment()` is not a valid fix.

Any idea?

**Comment by linzhp** [comment]
Sorry for late reply. Did you install the [SimPy](https://simpy.readthedocs.org/en/latest/) package?

**Comment by monperrus** [comment]
Yes:

```
$ python
Python 2.7.11 (default, Dec  9 2015, 00:29:25) 
[GCC 5.3.1 20151205] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import SimPy
>>> SimPy.__version__
'2.3.1'
>>> 
```

is that correct?

**Comment by linzhp** [comment]
Did you install simpy for Python 3?

**Comment by monperrus** [comment]
python3-simpy3 is the solution!

created a PR to clarify.

Thanks, --Martin

**Comment by linzhp** [comment]
Glad you figured it out. Thanks for #4
