### ISSUE TITLE
Indentation error

### ISSUE THREAD

**Issue by malembetirick** [linzhp/Codevo3#7]
before the Last line of code:
with open(os.path.join('output/src', class_name + '.java'), 'w') as java_file:
    ^
IndentationError: unexpected indent

**Comment by linzhp** [comment]
Which version of Python did you use for this?

**Comment by malembetirick** [comment]
Python 2.7.

2016-01-24 7:49 GMT+01:00 Zhongpeng Lin <notifications@github.com>:

**Comment by malembetirick** [comment]
On windows10 OS, i installed python 3.4, and i have issue to install Numpy
python module "Microsoft c++ 10 required", i tried to install Microsoft c++
10 on my windows system, but without succeed. so i uninstall python 3.4,
and i install python 2.7, with this i have the errors that i specified a
day ago.

Thanks for your understanding

2016-01-24 18:21 GMT+01:00 Rick Malembeti <malembetirick@gmail.com>:

**Comment by linzhp** [comment]
If you use Windows, the best way to install python is to use one of those
Scientific Python distributions, such as Anaconda. Those distributions will
have NumPy, NetworkX etc precompiled for you, so you don't need C++
compiler. Anaconda has Python 3.x version.

On Sun, Jan 24, 2016 at 9:42 AM, malembetirick <notifications@github.com>
wrote:

> On windows10 OS, i installed python 3.4, and i have issue to install Numpy
> python module "Microsoft c++ 10 required", i tried to install Microsoft c++
> 10 on my windows system, but without succeed. so i uninstall python 3.4,
> and i install python 2.7, with this i have the errors that i specified a
> day ago.
>
> Thanks for your understanding
>
>
> 2016-01-24 18:21 GMT+01:00 Rick Malembeti <malembetirick@gmail.com>:
>
> > Python 2.7.
> >
> > 2016-01-24 7:49 GMT+01:00 Zhongpeng Lin <notifications@github.com>:
> >
> >> Which version of Python did you use for this?
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/linzhp/Codevo3/issues/7#issuecomment-174261441>.
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linzhp/Codevo3/issues/7#issuecomment-174322993>.
>



-- 
Regards

*Zhongpeng Lin*

**Comment by malembetirick** [comment]
Thank you

2016-01-24 20:55 GMT+01:00 Zhongpeng Lin <notifications@github.com>:
