### ISSUE TITLE
issue with the growing number of steps Codevo simulate

### ISSUE THREAD

**Issue by malembetirick** [linzhp/Codevo3#8]
when i specify a little number, like 10 or 20, as value of entry, the folder output is generated, with success, but when i specify in entry the value "200000", in few minutes, an error about "ExpressionStatement isn't defined ", is returned, that's a capture of the error.
i use anaconda with python  version 3.5
Thank u
![capture du 2016-02-03 20-21-04](https://cloud.githubusercontent.com/assets/6019219/12794096/c1aaaea2-cab3-11e5-86fd-d532e04ebb71.png)

**Comment by linzhp** [comment]
It looks like your version of PLYJ doesn't have changes from https://github.com/musiKk/plyj/pull/28. Try checking out the HEAD revision of PLYJ and run again.

**Comment by malembetirick** [comment]
Thank u

2016-02-05 1:22 GMT+01:00 Zhongpeng Lin <notifications@github.com>:
