### ISSUE TITLE
codevo issue to generate java src

### ISSUE THREAD

**Issue by malembetirick** [linzhp/Codevo3#9]
I have an issue to generate java src folder, when i launch the script python simulate.py 200000, this script just generate the output folder with csv files, even if i uncomment the last 2 lines of the python file simulate.

Thank u

**Comment by linzhp** [comment]
Sorry, I changed the code without updating the doc. Now you should pass `-s` option to generate the source code. 

I just updated the README at ee25205ce35edd51f5c1dd588fc91858da4be81e and 77b142d1d8ed17a8987dcdb2303cf02d448628be

Let me know if you still have problems
